baseURL = 'https://blog.benligiray.com/'
languageCode = 'en-us'
title = 'ğŸ³ blog.benligiray.com'
theme = 'ananke'

[markup.goldmark.renderer]
  unsafe= true

[params]
  custom_css = ["custom.css"]
  body_classes = "palatino lh-copy bg-near-white"
  post_content_classes = "palatino lh-copy bg-near-white"
